on:
  push:
  #  branches:
  #    - master
  pull_request:
    branches:
      - master

name: render

jobs:
  render:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    name: render

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - name: Install renv
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          install.packages(c('renv', 'remotes', 'BiocManager'))
        shell: Rscript {0}
        
      - name: Cache renv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-1-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-1-

      - name: Restore renv
        run: |
          renv::restore()
        shell: Rscript {0}
        
      # This lets us augment with additional dependencies
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Session info
        run: |
          install.packages('sessioninfo', Ncpus = 2L)
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Render site
        run: |
          install.packages('rmarkdown', Ncpus = 2L)
          rmarkdown::render(input = "index.Rmd")
        shell: Rscript {0}

      - name: Prepare files to deploy
        run: |
          mkdir _site
          cp -r img libs my-theme.css index.html _site/

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          apt-get update && apt-get -y install rsync

      - name: Deploy ðŸš€
        #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
